[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
    external_node_modules = ["@ampproject/toolbox-optimizer", "sharp"]
  included_files = ["public/locales/en/*.json", "public/locales/zh/*.json", "/var/task/next-i18next.config.js"]